# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
development:
  secret_key_base: f238c5acb0a2be14e247f090dddae36647d4d84fc2f9ec92d95d70caf62375dbbc9b97cc7118abd37036e0ef2e64b7a5a1de11376ef04cef4c06f52a6daef3f3
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://localhost:3000
test:
  secret_key_base: 834e9e84a1cfd863f521ac2d290d2412ee82829207c69b4421b49fb4f41a4b4c54b1015c165644e50fda978f204711d2f0062c69771924add0f2049b8829681c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # paypal_host: https://www.paypal.com
  app_host: https://whispering-wave-7204.herokuapp.com/
  paypal_host: https://www.sandbox.paypal.com
